# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: WindowsTesting

stages:
    - stage: BuildingJavaCode
      jobs:
      - job: BuildingJavaCodeJob
        timeoutInMinutes: 10
        steps:
        - script: echo $(Build.BuildId)
          displayName: 'Display The Build-ID'

        - script: ls -al && pwd
          displayName: 'List Files & Current Working Directory'
        
        - script: ls -al && chmod 700 build.sh && sudo bash ./build.sh && ls -al
          displayName: 'Run the build script'

        - script: ls -al && mv ROOT.war ROOT$(Build.BuildId).war && ls -al
          displayName: 'List Files & Rename ROOT.war'

        - script: cp ROOT$(Build.BuildId).war /home/ubuntu/agent/testdir && ls -al /home/ubuntu/agent/testdir
          displayName: 'Copy WAR to testdir folder'

    - stage: DeleteTheRepo
      jobs:
      - job: DeleteTheRepoCntent
        timeoutInMinutes: 10
        steps:
         - checkout: none
         - script: cd /home/ubuntu/agent/_work/1/s && sudo rm -rf src
           displayName: 'Remove Files'

        #  - script: cd /artifacts && sudo rm -f *.war
        #    displayName: 'Remove Files From tmp Folder'
          
        # - task: CopyFiles@2
        #   inputs:
        #     Contents: 'ROOT$(Build.BuildId).war'
        #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
        #     OverWrite: true
        #   displayName: 'Copying WAR file to ArtifactStagingDirector'          
